title = "Life Ledger Gitleaks Config"

[allowlist]
  description = "Global allowlist"
  paths = [
    '''(.*/)?\.env\.example''',
    '''(.*/)?test/.*''',
    '''(.*/)?src/test/.*''',
    '''(.*/)?tests/.*''',
  ]
